import { adminFetch } from '../../api/client';
import { trans } from '../../i18n/i18n';
import type { ParkingLot, ParkingSlot } from '../../interfaces/models';
import { loadPostOffices } from '../../utils/postal';

export async function renderLotsSection(container: HTMLElement, token: string): Promise<void> {
    container.innerHTML = '';
    const heading = document.createElement('h3'); heading.textContent = trans('admin.lotsHeading'); container.appendChild(heading);
    const list = document.createElement('ul'); list.className = 'admin-list'; container.appendChild(list);
    const res = await adminFetch('resource=lots', token); const lots: ParkingLot[] = await res.json();
    let editingId: number | null = null; let slots: ParkingSlot[] = [];
    const form = document.createElement('form'); form.className = 'auth-form';
    const addField = (labelKey: string, input: HTMLElement): void => { const field = document.createElement('label'); field.className = 'lot-field'; const label = document.createElement('span'); label.textContent = trans(labelKey); field.append(label, input); form.appendChild(field); };
    const textInput = (placeholder: string): HTMLInputElement => { const input = document.createElement('input'); input.className = 'text-input'; input.placeholder = trans(placeholder); input.required = true; return input; };
    const nameInput = textInput('admin.lotName'); const addressInput = textInput('admin.lotAddress');
    const postalInput = textInput('admin.lotPostalCode'); postalInput.type = 'text'; postalInput.inputMode = 'numeric'; postalInput.maxLength = 5; postalInput.pattern = '\\d{5}';
    const cityInput = textInput('admin.lotCity'); cityInput.disabled = true;
    const infoInput = document.createElement('textarea'); infoInput.className = 'text-input'; infoInput.placeholder = trans('admin.lotInfo');
    postalInput.addEventListener('input', async () => { cityInput.value = (await loadPostOffices()).get(postalInput.value.trim()) ?? ''; });
    const capacityInput = textInput('admin.lotCapacity'); capacityInput.type = 'number'; capacityInput.disabled = true;
    const price3hInput = textInput('admin.lotPriceFirst3h'); price3hInput.type = 'number'; price3hInput.step = '0.01';
    const priceExtraInput = textInput('admin.lotPriceExtraHour'); priceExtraInput.type = 'number'; priceExtraInput.step = '0.01';
    const submitButton = document.createElement('button'); submitButton.className = 'submit-button'; submitButton.type = 'submit'; submitButton.textContent = trans('admin.add');
    addField('admin.lotName', nameInput); addField('admin.lotAddress', addressInput); addField('admin.lotPostalCode', postalInput); addField('admin.lotCity', cityInput); addField('admin.lotInfo', infoInput); addField('admin.lotCapacity', capacityInput); addField('admin.lotPriceFirst3h', price3hInput); addField('admin.lotPriceExtraHour', priceExtraInput);
    const slotsLabel = document.createElement('div'); slotsLabel.className = 'slots-label'; const slotsHeading = document.createElement('strong'); slotsHeading.textContent = trans('admin.parkingSlots'); const autoSlotsText = document.createElement('span'); autoSlotsText.textContent = trans('admin.autoAddSlots'); const autoSlotsInput = document.createElement('input'); autoSlotsInput.type = 'number'; autoSlotsInput.min = '1'; autoSlotsInput.value = '1'; autoSlotsInput.className = 'slot-count-input'; const autoSlotsButton = document.createElement('button'); autoSlotsButton.type = 'button'; autoSlotsButton.className = 'submit-button'; autoSlotsButton.textContent = trans('admin.addSlots'); slotsLabel.append(slotsHeading, autoSlotsText, autoSlotsInput, autoSlotsButton); form.appendChild(slotsLabel);
    const slotGrid = document.createElement('div'); slotGrid.id = 'slot-grid'; slotGrid.className = 'slot-grid'; form.appendChild(slotGrid);
    const renderSlots = (): void => { slotGrid.innerHTML = ''; for (const [index, slot] of slots.entries()) { const slotItem = document.createElement('div'); slotItem.className = 'slot-item'; const title = document.createElement('strong'); title.textContent = `${trans('admin.slot')} ${index + 1}`; const name = document.createElement('input'); name.type = 'text'; name.className = 'text-input'; name.placeholder = trans('admin.slotName'); name.value = slot.name ?? ''; name.addEventListener('input', () => { slot.name = name.value; }); const activeLabel = document.createElement('label'); const active = document.createElement('input'); active.type = 'checkbox'; active.checked = Boolean(slot.is_active); active.addEventListener('change', () => { slot.is_active = active.checked; }); activeLabel.append(active, document.createTextNode(` ${trans('admin.slotActive')}`)); const deleteButton = document.createElement('button'); deleteButton.type = 'button'; deleteButton.className = 'submit-button'; deleteButton.textContent = trans('admin.delete'); deleteButton.addEventListener('click', () => { slots.splice(index, 1); renderSlots(); }); slotItem.append(title, name, activeLabel, deleteButton); slotGrid.appendChild(slotItem); } capacityInput.value = String(slots.length); };
    autoSlotsButton.addEventListener('click', () => { const count = Number(autoSlotsInput.value); if (Number.isInteger(count) && count > 0) { slots.push(...Array.from({ length: count }, () => ({ name: null, is_active: true }))); renderSlots(); } });
    form.appendChild(submitButton); container.appendChild(form);
    const resetForm = (): void => { editingId = null; form.reset(); slots = []; renderSlots(); submitButton.textContent = trans('admin.add'); };
    form.addEventListener('submit', async (event) => { event.preventDefault(); const body = JSON.stringify({ name: nameInput.value.trim(), address: addressInput.value.trim(), postal_code: postalInput.value.trim(), info: infoInput.value.trim(), price_first_3h: price3hInput.value, price_per_extra_hour: priceExtraInput.value, slots }); if (editingId) await adminFetch(`resource=lots&id=${editingId}`, token, { method: 'PUT', body }); else await adminFetch('resource=lots', token, { method: 'POST', body }); resetForm(); void renderLotsSection(container, token); });
    for (const lot of lots) { const item = document.createElement('li'); item.textContent = `${lot.name} (${lot.city}) — ${lot.capacity} ${trans('admin.slotsSuffix')} `; const editButton = document.createElement('button'); editButton.className = 'submit-button'; editButton.type = 'button'; editButton.textContent = trans('admin.edit'); editButton.addEventListener('click', async () => { editingId = lot.id; nameInput.value = lot.name; addressInput.value = lot.address; postalInput.value = lot.postal_code; cityInput.value = lot.city; infoInput.value = lot.info ?? ''; price3hInput.value = String(lot.price_first_3h); priceExtraInput.value = String(lot.price_per_extra_hour); const slotsRes = await adminFetch(`resource=slots&lot_id=${lot.id}`, token); slots = await slotsRes.json(); renderSlots(); submitButton.textContent = trans('admin.save'); }); const deleteButton = document.createElement('button'); deleteButton.className = 'submit-button'; deleteButton.type = 'button'; deleteButton.textContent = trans('admin.delete'); deleteButton.addEventListener('click', async () => { await adminFetch(`resource=lots&id=${lot.id}`, token, { method: 'DELETE' }); void renderLotsSection(container, token); }); item.append(editButton, deleteButton); list.appendChild(item); }
}