import { adminFetch, validateEmailInput } from '../../api/client';
import { trans } from '../../i18n/i18n';
import type { AdminUser } from '../../interfaces/models';
import { loadPostOffices } from '../../utils/postal';

export async function renderUsersSection(container: HTMLElement, token: string, actorRole: string): Promise<void> {
    container.innerHTML = ''; const heading = document.createElement('h3'); heading.textContent = trans('admin.usersHeading'); container.appendChild(heading); const list = document.createElement('ul'); list.className = 'admin-list'; container.appendChild(list);
    const res = await adminFetch('resource=users', token); const users: AdminUser[] = await res.json(); let editingId: number | null = null;
    const form = document.createElement('form'); form.className = 'auth-form'; const input = (placeholder: string): HTMLInputElement => { const field = document.createElement('input'); field.className = 'text-input'; field.placeholder = trans(placeholder); field.required = true; return field; };
    const regInput = input('details.regNumberPlaceholder'); const emailInput = input('login.emailPlaceholder'); emailInput.type = 'email'; const firstInput = input('details.firstNamePlaceholder'); const lastInput = input('details.lastNamePlaceholder'); const postalInput = input('details.postalCodePlaceholder'); postalInput.type = 'text'; postalInput.inputMode = 'numeric'; postalInput.maxLength = 5; postalInput.pattern = '\\d{5}'; const cityInput = input('details.cityPlaceholder'); cityInput.disabled = true;
    postalInput.addEventListener('input', async () => { cityInput.value = (await loadPostOffices()).get(postalInput.value.trim()) ?? ''; });
    const roleSelect = document.createElement('select'); roleSelect.className = 'text-input'; for (const role of actorRole === 'owner' ? ['admin', 'customer'] : ['customer']) { const option = document.createElement('option'); option.value = role; option.textContent = trans(`admin.role${role[0].toUpperCase()}${role.slice(1)}`); roleSelect.appendChild(option); }
    const statusSelect = document.createElement('select'); statusSelect.className = 'text-input'; for (const status of ['confirmed', 'pending']) { const option = document.createElement('option'); option.value = status; option.textContent = trans(`admin.status${status[0].toUpperCase()}${status.slice(1)}`); statusSelect.appendChild(option); }
    const submitButton = document.createElement('button'); submitButton.className = 'submit-button'; submitButton.type = 'submit'; submitButton.textContent = trans('admin.add'); form.append(regInput, emailInput, firstInput, lastInput, postalInput, cityInput, roleSelect, statusSelect, submitButton); container.appendChild(form);
    const resetForm = (): void => { editingId = null; form.reset(); submitButton.textContent = trans('admin.add'); };
    form.addEventListener('submit', async (event) => { event.preventDefault(); if (!validateEmailInput(emailInput)) return; const body = JSON.stringify({ reg_number: regInput.value.trim(), email: emailInput.value.trim(), first_name: firstInput.value.trim(), last_name: lastInput.value.trim(), postal_code: postalInput.value.trim(), role: roleSelect.value, status: statusSelect.value }); if (editingId) await adminFetch(`resource=users&id=${editingId}`, token, { method: 'PUT', body }); else await adminFetch('resource=users', token, { method: 'POST', body }); resetForm(); void renderUsersSection(container, token, actorRole); });
    for (const user of users) { const item = document.createElement('li'); item.textContent = `${user.first_name ?? ''} ${user.last_name ?? ''} — ${user.email ?? ''} — ${user.city ?? ''} (${user.role}) `; const canManage = actorRole === 'owner' ? user.role !== 'owner' : user.role === 'customer'; if (!canManage) { list.appendChild(item); continue; } const editButton = document.createElement('button'); editButton.className = 'submit-button'; editButton.type = 'button'; editButton.textContent = trans('admin.edit'); editButton.addEventListener('click', () => { editingId = user.id; regInput.value = user.reg_number ?? ''; emailInput.value = user.email ?? ''; firstInput.value = user.first_name ?? ''; lastInput.value = user.last_name ?? ''; postalInput.value = user.postal_code ?? ''; cityInput.value = user.city ?? ''; roleSelect.value = user.role; statusSelect.value = user.status; submitButton.textContent = trans('admin.save'); }); const deleteButton = document.createElement('button'); deleteButton.className = 'submit-button'; deleteButton.type = 'button'; deleteButton.textContent = trans('admin.delete'); deleteButton.addEventListener('click', async () => { await adminFetch(`resource=users&id=${user.id}`, token, { method: 'DELETE' }); void renderUsersSection(container, token, actorRole); }); item.append(editButton, deleteButton); list.appendChild(item); }
}